<a href="https://colab.research.google.com/github/Parag003/Ml_lab/blob/main/Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


arr = np.array([1,2,3,4,5,6]);
reversed_arr = arr[::-1]

print(reversed_arr)


[6 5 4 3 2 1]


In [ ]:
# flatten

array1 = np.array([1,2,3,4,5,6])

flattened_array = array1.flatten()

print(flattened_array)

[1 2 3 4 5 6]


In [ ]:
# compare

arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[1,2],[3,4]])

comparison = np.array_equal(arr1,arr2)

print(comparison)

True


In [ ]:
x= np.array([1,2,3,4,5,1,2,1,1,1])

most_freq = np.bincount(x).argmax()
indices = np.where(x == most_freq)[0]
print(most_freq,indices)

1 [0 5 7 8 9]


In [ ]:
gfg = np.matrix('[4,1,9;12,3,1;4,5,6]')

# sum
total_sum = gfg.sum()

# sum row wise
row_sum = gfg.sum(axis=1)

# sum of all column wise
colum_sum  = gfg.sum(axis=0)

print(total_sum,row_sum,colum_sum)

45 [[14]
 [16]
 [15]] [[20  9 16]]


In [ ]:
n_array = np.array([[55,25,15], [30, 44, 2], [11, 45, 77]])

sum_diag = np.trace(n_array)

eigenvalues , eigenvectors = np.linalg.eig(n_array)

inverse_matrix = np.linalg.inv(n_array)


determinant = np.linalg.det(n_array)

print(sum_diag,eigenvalues,eigenvectors,inverse_matrix,determinant)

176 [98.16835147 28.097044   49.73460452] [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]] [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]] 137180.0000000001


In [ ]:
p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])

product_1 = np.dot(p,q)

covariance = np.cov(p.flatten(),q.flatten())

print(product_1,covariance)

[[16 19]
 [26 31]] [[0.66666667 1.        ]
 [1.         1.66666667]]


In [ ]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])


inner_product = np.inner(x,y)

outer_prod= np.outer(x,y)


cartesian_prod = np.array(np.meshgrid(x.flatten(),y.flatten())).T.reshape(-1,2)
print(inner_product,outer_prod,cartesian_prod)

[[17 52]
 [13 62]] [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]] [[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


In [ ]:
array = np.array([[1,-2,3] ,[-4,-5,-6]])

abs_array = np.abs(array)

In [ ]:
array = np.array([[1,-2,3] ,[-4,-5,-6]])

flattened_array = array.flatten()

percen_25 = np.percentile(flattened_array,25)
percen_50 = np.percentile(flattened_array,50)
percen_75 = np.percentile(flattened_array,75)

percen_25_col = np.percentile(array,25,axis=0)
percen_50_col = np.percentile(array,50,axis=0)
percen_75_col = np.percentile(array,75,axis=0)

percen_25_row = np.percentile(array,25,axis=1)
percen_50_row = np.percentile(array,50,axis=1)
percen_75_row = np.percentile(array,75,axis=1)

print(percen_25,percen_50,percen_75)
print(percen_25_col,percen_50_col,percen_75_col)
print(percen_25_row,percen_50_row,percen_75_row)


-4.75 -3.0 0.25
[-2.75 -4.25 -3.75] [-1.5 -3.5 -1.5] [-0.25 -2.75  0.75]
[-0.5 -5.5] [ 1. -5.] [ 2.  -4.5]


In [ ]:
mean_flat = np.mean(flattened_array)
mean_col = np.mean(array,axis=0)
mean_row = np.mean(array,axis=1)

median_flat = np.median(flattened_array)
median_col = np.median(array,axis=0)
median_row = np.median(array,axis=1)

std_flat = np.std(flattened_array)
std_col = np.std(array,axis=0)
std_row = np.std(array,axis=1)
print(mean_flat,mean_col,mean_row)
print(median_flat,median_col,median_row)
print(std_flat,std_col,std_row)

-2.1666666666666665 [-1.5 -3.5 -1.5] [ 0.66666667 -5.        ]
-3.0 [-1.5 -3.5 -1.5] [ 1. -5.]
3.2360813064912666 [2.5 1.5 4.5] [2.05480467 0.81649658]


In [ ]:
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

floor_values = np.floor(a)


cieling_val = np.ceil(a)

trunca_val = np.trunc(a)


rounde_val = np.round(a)

print(floor_values,cieling_val,trunca_val,rounde_val)

In [ ]:
array = np.array([10, 52, 62, 16, 16, 54, 453])

sorted_arr = np.sort(array)

print(sorted_arr)


In [ ]:
indices_sort_Arr = np.argsort(array)

print(indices_sort_Arr)

[[1 0 2]
 [2 1 0]]


In [ ]:
smallest_elemen = np.partition(array , 4 )[:4]
print(smallest_elemen)

In [ ]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

In [ ]:
integer_elem = array[array == array.astype(int)]
print(integer_elem)

[1. 2. 3. 2.]


In [ ]:
float_elem = array[array != array.astype(int)]
print(float_elem)

[1.2 2.2]


In [ ]:
!pip install PIL


ERROR: Could not find a version that satisfies the requirement PIL (from versions: none)
ERROR: No matching distribution found for PIL


In [ ]:
!pip install os
import os
os.listdir()


ERROR: Could not find a version that satisfies the requirement os (from versions: none)
ERROR: No matching distribution found for os


['.config', 'sample_img.jpg', 'sample_data']

In [ ]:

# Ques 4 image handling

from  PIL import Image

import numpy as np
path_to_image = "sample_img.jpg"
save_path = "sample_image.txt"

def img_to_array(path_to_image , save_path):
    img = Image.open(path_to_image)
    img_array = np.array(img)
    if len(img_array.shape) == 2:
      mode ='L'
    else:
      mode = 'RGB'



    np.savetxt(save_path,img_array.flatten() , fmt='%d' , header = f"{mode} {img_array.shape[0]} {img_array.shape[1]}")

    print(f"image saved at {save_path}")


img_to_array(path_to_image,save_path)







image saved at sample_image.txt
